apiVersion: v1
kind: Namespace
metadata:
  name: devopsagent
---
apiVersion: v1
kind: Secret
metadata:
  name: azdevops
  namespace: devopsagent
data:
  AZP_URL: aHR0cHM6Ly9kZXYuYXp1cmUuY29tL2phaXZlcmpvY2FzbWVuOTQ= # Base64 encoded URL
  AZP_POOL: bGludXgtY29udGFpbmVycy1ha3M= # Base64 encoded Pool
  AZP_TOKEN: enk1NjJ1NjVzNHc0bW16M25iaoRieGg0c3U3NGJjd3F2NmI2YWhhcWpvd2w1amE= # Base64 encoded Token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  namespace: devopsagent
  labels:
    app: azdevops-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: jocasmenacr.azurecr.io/dockeragent:ubuntu-20.04
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_POOL
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock
